name: Publish Container to Docker Packages

# Documentation on the primary Action used here: https://github.com/marketplace/actions/publish-docker
# TODO MLF-CORE: Adapt the username, password and registry if you do not want to publish to Github Packages.
# TODO MLF-CORE: Note that for organization repositories the Github Container Registry needs to be enabled
# https://docs.github.com/en/packages/getting-started-with-github-container-registry/enabling-github-container-registry-for-your-organization

on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Reclaim space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name:  Functional-Genomics-Lab/notebook-template
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          snapshot: true
          tags: "latest"
